### PR TITLE
New analysis, feature importance

### PR DESCRIPTION
**Pull request by silburt**
Hey all,
I created a notebook which analyzes feature importance in the data set using PCA and also some plotting. Requires "plotly" for the 3D interactive visualizations though. Not sure if anyone has any better python interactive 3D plotting choices.

Ari

### CODE REVIEW

**Comment by dtamayo** [comment]
Just looked through it, this is great!  I’m still surprised the eccentricities matter so little.  I’d like to understand that better…

**Comment by silburt** [comment]
Agreed. I wonder if it might be useful to sample some extreme regions of parameter space? Certain papers (e.g. Eq.14 from Pu & Wu) have claimed that small increases in eccentricities (e.g. 0.01) have noticeable effects on stability. This dataset doesn't seem to demonstrate that fact.

**Comment by dtamayo** [comment]
Maybe it’s saying that we haven’t integrated long enough.  Perhaps you need longer timescales to random walk and it will show up more clearly when we do longer runs…

**Comment by dtamayo** [comment]
I’m running some tests now to see how big a dataset we can generate.  I think that will determine how much of parameter space we can sample, but I’m tempted to keep things fairly constrained.

**Comment by silburt** [comment]
Looking in more detail at the Pu and Wu paper, for their initial dataset they simulate 7-planet systems for 10^7 years, with the innermost planet at 0.1AU. That's no so much different from 10^6 years with the innermost planet at 0.05AU. They drew eccentricity from Rayleigh with sigma E [0,0.05].

Seems to me like the only variables that are substantially different from our investigation and theirs is the number of planets and the eccentricity of each planet. Simulating for more time may reveal new insight, but will also take that ~10x longer anytime we want to re-run the dataset with slightly different parameters to compare to our original dataset.

**Comment by dtamayo** [comment]
This preliminary dataset runs for 1e6 orbits.  At 0.1 AU, one orbit is ~0.03 yrs, so they’re running for ~ 3e8 orbits.  I just want to make sure we get things right before dumping a lot of computer time into the big dataset

**Comment by silburt** [comment]
Ah. I misread orbits and years in explore.ipynb. Got it.

**Pull request merged**
